### ISSUE TITLE
Stickers from same server get sent as png/gif

### ISSUE THREAD

**Issue by jericjan** [An00nymushun/DiscordFreeStickers#3]
When I try to send a sticker that's from the same server I'm in, it sends the url of that sticker. DiscordFreeEmojis doesn't do this so I was wondering maybe this is a bug. Or is it not possible due to the way stickers work?

**Comment by An00nymushun** [comment]
This doesn't happen to me, does it happen for you on every server you are in? (with local stickers)

**Comment by jericjan** [comment]
Yes.

**Comment by An00nymushun** [comment]
What kind of nitro do you have if any?

**Comment by jericjan** [comment]
I don't have any active nitro subscriptions on my account.

**Comment by An00nymushun** [comment]
Try disabling every other plugin and restart your discord like that, check if it works after that.

**Comment by jericjan** [comment]
Tried it. Restarted discord. The same thing happened.

**Comment by An00nymushun** [comment]
Please test it on my server https://discord.gg/zJQuMMKXjN
Ping me too

**Comment by Fr3akyMurk** [comment]
Same thing occurs for me.

**Comment by An00nymushun** [comment]
I'm closing this issue due to the lack of information, if you encounter something like this, please open a new issue and follow the template.

**Comment by An00nymushun** [comment]
I think I have found the issue

**Comment by An00nymushun** [comment]
Should be fixed now

**Comment by Fr3akyMurk** [comment]
> Should be fixed now

Still isn't fixed, i downloaded the new plugin from the code page as a zip and dropped it in my plugins folder and it still sends both the sticker and the GIF.

**Comment by An00nymushun** [comment]
> > Should be fixed now
> 
> Still isn't fixed, i downloaded the new plugin from the code page as a zip and dropped it in my plugins folder and it still sends both the sticker and the GIF.

That is not the same issue as this, this is just about sending stickers as link even when you have permission to send the sticker in the server.

Open a new issue with your problem.
