### ISSUE TITLE
FreeStickers could not be started

### ISSUE THREAD

**Issue by AsahiOw** [An00nymushun/DiscordFreeStickers#34]
**Describe the bug**
The plugin can not run after the newest discord update.

**To Reproduce**
Enable the plugin through BetterDiscord - Plugins

**Steps to reproduce the behavior:**

1. Go to the discord setting.
2. Select Plugins in BETTERDISCORD.
3. Enable FreeStickers.

**Expected behavior**
FreeSticker has been enabled.

**Screenshot**
![Screenshot 2023-10-26 134037](https://github.com/An00nymushun/DiscordFreeStickers/assets/118656767/f1ee5477-31ca-4091-ad85-8721d1438dfd)

**Client**
Stable 240372 (63f8ac7)
Plugin Version [1.4.0]
BD Version Core v1.9.4

**Comment by FerLuisxd** [comment]
having the same issue :(

**Comment by FerLuisxd** [comment]
![image](https://github.com/An00nymushun/DiscordFreeStickers/assets/29811965/f6834b5d-77f5-4f60-8b73-5a3f83efab11)
Seems that is a known issue? Woah but it is huge

**Comment by AsahiOw** [comment]
with the newest BT v1.9.5, the issues with this plugin have been fixed

**Comment by wifekurumi** [comment]
weird, My BD core v1.9.5 and Plugin is v1.4.0, but the issues still happens.
![image](https://github.com/An00nymushun/DiscordFreeStickers/assets/115228055/dd0e8890-1b1b-4eac-846c-95b3309ae0d8)
is it because of the update of discord?
